### ISSUE TITLE
is there reason to cast image to int not float?

### ISSUE THREAD

**Issue by aandreev0** [kdizon/image-contrast#2]
https://github.com/kdizon/image-contrast/blob/6cad7768f46cf93268922c0b8ab78882abdcdcc5/sd.m#L15

i wonder if there was a reason to cast image to Integer type, and not a float, since you do float operations later (as normalize image to 0...1, then to 0...65e3)

**Comment by kdizon** [comment]
Mostly because we know the value of the image can't be negative, so using unassigned lets you represent a wider range of (positive) numbers

**Comment by aandreev0** [comment]
ok got it. makes sense
